{
 "title": "hhub-price-summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appname", "label": "应用", "query": "hhub-price" },
   {
    "name": "source",
    "label": "来源",
    "query": {
     "query": "label_values(crs_price_request_bucket{envtype=\"$envtype\",app=\"$appname\"},source)"
    }
   },
   {
    "name": "channel",
    "label": "渠道",
    "query": {
     "query": "label_values(crs_price_request_bucket{envtype=\"$envtype\",app=\"$appname\",source=~\"$source\"},channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "近一分钟房价查询产品数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(crs_price_product_count_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"500.0\",channel=~\"$channel\"}[1m])) by (channel) ) > 0",
     "legendFormat": "{{channel}} - 产品数 [1,500]"
    },
    {
     "expr": "(sum(increase(crs_price_product_count_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"1500.0\",channel=~\"$channel\"}[1m])) by (channel) - sum(increase(crs_price_product_count_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"500.0\",channel=~\"$channel\"}[1m])) by (channel) ) > 0",
     "legendFormat": "{{channel}} - 产品数 (500,1500]"
    },
    {
     "expr": "(sum(increase(crs_price_product_count_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"+Inf\",channel=~\"$channel\"}[1m])) by (channel) - sum(increase(crs_price_product_count_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"1500.0\",channel=~\"$channel\"}[1m])) by (channel) ) > 0",
     "legendFormat": "{{channel}} - 产品数 >1500"
    }
   ]
  },
  {
   "title": "近一分钟房价查询天数的请求量",
   "type": "graph",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"1.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 1天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"3.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"1.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 3天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"7.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"3.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 7天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"15.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"7.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 15天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"30.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"15.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 30天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"60.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"30.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 60天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"90.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"60.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 90天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"180.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"90.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 180天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"360.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"180.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 360天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"420.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"360.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 420天请求量"
    },
    {
     "expr": "(sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"+INF\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) - sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",le=\"420.0\",channel=~\"$channel\",source=~\"$source\"}[1m])) by (channel) ) > 0 ",
     "legendFormat": "{{channel}} - 大于420天请求量"
    }
   ]
  },
  {
   "title": "所选时段内房价查询天数的分布",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",channel=~\"$channel\",source=~\"$source\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "房价查询天数的分布热力图",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(crs_price_request_bucket{app=\"$appname\",envtype=\"$envtype\",channel=~\"$channel\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}