{
 "title": "image-list",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "appname",
    "label": "application",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{container!~\"|POD\",namespace=~\"$namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "pod list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "宿主机POD数量",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"$appname.+\",namespace=~\"$namespace\"}) by (host_ip,node)"
    }
   ]
  },
  {
   "title": "应用配额信息",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(kube_deployment_spec_replicas{deployment=~\"$appname\",namespace=~\"$namespace\"},\"container\",\"$1\",\"deployment\",\"(.*)\")"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$appname.+\",namespace=~\"$namespace\",resource=\"cpu\"}) by (namespace,container)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$appname.+\",namespace=~\"$namespace\",resource=\"memory\"}) by (namespace,container)"
    },
    {
     "expr": "label_replace(kube_deployment_status_replicas_available{deployment=~\"$appname\",namespace=~\"$namespace\"},\"container\",\"$1\",\"deployment\",\"(.*)\")"
    },
    {
     "expr": "label_replace(kube_deployment_spec_strategy_rollingupdate_max_surge{deployment=~\"$appname\",namespace=~\"$namespace\"},\"container\",\"$1\",\"deployment\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Pod Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$appname.+\"}) by (host_ip,node,pod,namespace,pod,pod_ip,datacenter)"
    },
    {
     "expr": "kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$appname.+\"} * 1000"
    },
    {
     "expr": " increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$appname.+\"}[5m])"
    }
   ]
  },
  { "title": "image list & domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "应用域名信息",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_ingress_path{namespace=~\"$namespace\",ingress=~\"$appname.*\"}) by(datacenter,namespace,host,path,ingress)"
    }
   ]
  },
  {
   "title": "应用容器镜像",
   "type": "table",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$appname.+\", container!~\"|POD\", image!=\"\"}) by (container,namespace,image) "
    }
   ]
  }
 ]
}