{
 "title": "legacy-app-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"oss.+\"},namespace)"
    }
   },
   {
    "name": "appname",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count,service)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\",namespace=~\"$namespace\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"},pod)"
    }
   },
   {
    "name": "localcache",
    "label": "Local Cache",
    "query": {
     "query": "label_values(cache_size{service=\"$appname\",instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " Number of copies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"$appname\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Application Node and Pod Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=\"$appname\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$appname.+\",namespace=~\"$namespace\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$appname.+\",namespace=\"$namespace\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Overview of traffic of each node component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\",namespace=~\"$namespace\"}[2m])) ",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Redis Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\",namespace=~\"$namespace\"}[2m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_consumed_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} - consumed"
      },
      {
       "expr": "sum(irate(rabbitmq_published_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} - published"
      }
     ]
    },
    {
     "title": "Logback Log",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\",namespace=~\"$namespace\"}[2m]))\n",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Logback Level",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance,level)",
       "legendFormat": "{{instance}} - {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview of key indicators of each node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "YoungGC Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "times/minute" } },
     "yaxes": [
      { "format": "times/minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",namespace=~\"$namespace\",action=~\".*minor.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "New Generation Memory Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OldGC Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "times/minute" } },
     "yaxes": [
      { "format": "times/minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",namespace=~\"$namespace\",action=~\".*major.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Old Generation Memory Allocation (Promotion Object)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Maximum Pause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$appname\",namespace=~\"$namespace\"} > 0",
       "legendFormat": "{{instance}} - {{cause}}"
      }
     ]
    },
    {
     "title": "Old Generation Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$appname\",namespace=~\"$namespace\",id=~\"[a-zA-Z0-9\\\\s]+Old[a-zA-Z0-9\\\\s]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " sum(jvm_memory_used_bytes{service=\"$appname\",area=\"heap\",namespace=~\"$namespace\"}) by (instance) / sum(jvm_memory_max_bytes{service=\"$appname\",area=\"heap\",namespace=~\"$namespace\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$appname\",namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File descriptors opened by the process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open{service=\"$appname\",namespace=~\"$namespace\"} OR process_files_open_files{service=\"$appname\",namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Container OOM/Restart Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=\"$appname\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} - OOMKilled"
      },
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"$appname\",namespace=~\"$namespace\"}[3m])",
       "legendFormat": "{{pod}} - Restarted in the last 3 minutes"
      }
     ]
    },
    {
     "title": "Tomcat thread pool usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(tomcat_threads_busy{service=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}/ tomcat_threads_config_max) OR (tomcat_threads_busy_threads{service=~\"$appname\",namespace=~\"$namespace\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}/ tomcat_threads_config_max_threads)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat Active Threads",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{service=~\"$appname\",namespace=~\"$namespace\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} OR tomcat_threads_busy_threads{service=~\"$appname\",namespace=~\"$namespace\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node JVM Thread Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$appname\",namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}} - {{state}} Threads"
      }
     ]
    },
    {
     "title": "Cluster JVM Thread Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_threads_states_threads{service=\"$appname\",namespace=~\"$namespace\"}[1m])) by (state)",
       "legendFormat": "{{state}} Threads"
      }
     ]
    },
    {
     "title": " Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=~\"$appname\",namespace=~\"$namespace\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System LoadAvg in the last minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{service=~\"$appname\",namespace=~\"$namespace\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POD CPU usage",
     "type": "graph",
     "description": "Pod CPU usage statistics from k8s",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{container!~\"(POD|istio-proxy)\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[5m]) ) by (pod) / max( kube_pod_container_resource_limits{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\",resource=\"cpu\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD memory usage",
     "type": "graph",
     "description": "Pod memory usage statistics from k8s",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 77 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{ container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"} ) by (pod)/ max( kube_pod_container_resource_limits{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\",resource=\"memory\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD Network IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[3m])",
       "legendFormat": "{{pod}} - Sent Bytes"
      },
      {
       "expr": "irate(container_network_receive_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[3m])",
       "legendFormat": "{{pod}} - Received Bytes"
      }
     ]
    },
    {
     "title": "POD Disk IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{pod}} - Read Bytes"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{pod}} - Write Bytes "
      }
     ]
    },
    {
     "title": "Container CPU Throttled Periods %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[2m])\n /increase(container_cpu_cfs_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",namespace=~\"$namespace\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container CPU Throttled Time Per Period",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " irate(container_cpu_cfs_throttled_seconds_total{pod=~\"$appname.+\",namespace=~\"$namespace\"}[2m]) / 10",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP API Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP API Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP API Avg Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_sum{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (uri) / sum(irate(http_server_requests_seconds_count{service=\"$appname\",namespace=~\"$namespace\"}[2m])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Node JVM & Key Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU Throttled Periods %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{container=~\"$appname\", pod=~\"$pod\",namespace=~\"$namespace\"}[2m])\n /increase(container_cpu_cfs_periods_total{container=~\"$appname\", pod=~\"$pod\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM memory pool maximum configuration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "{{id}}({{area}})"
    }
   ]
  },
  {
   "title": "GC Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "Young Gen bytes added per second"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "Old Gen bytes added per second"
    }
   ]
  },
  {
   "title": "JVM memory pool used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "{{id}}({{area}}) "
    }
   ]
  },
  {
   "title": "GC pause duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "{{action}} ({{cause}}) - Maximum pause duration"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m]) / rate(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{action}} ({{cause}}) - Average pause"
    }
   ]
  },
  {
   "title": "GC Reasons and Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "times/minute" } },
   "yaxes": [
    { "format": "times/minute" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[70s])",
     "legendFormat": "{{action}} ({{cause}}) "
    }
   ]
  },
  {
   "title": "Cumulative GC times in the selected period",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[$__range])) by(action,cause)",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Cumulative GC time consumed in the selected period",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 50 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[$__range])) by(action,cause) ",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Tomcat Thread Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR tomcat_threads_busy_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "Active thread (busy)"
    },
    {
     "expr": "tomcat_threads_config_max{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR tomcat_threads_config_max_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "Maximum number of threads"
    },
    {
     "expr": "tomcat_threads_current{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR tomcat_threads_current_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "Current number of threads"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR jvm_threads_daemon_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "jvm_threads_live{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR jvm_threads_live_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "Daemon + None Daemon Threads"
    },
    {
     "expr": "jvm_threads_peak{service=\"$appname\",instance=\"$instance\"} OR jvm_threads_peak_threads{service=\"$appname\",instance=\"$instance\"}",
     "legendFormat": "Peak number of threads"
    }
   ]
  },
  {
   "title": "Class loading statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_classes_unloaded_classes_total{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m]) OR increase(jvm_classes_unloaded_total{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "Class uninstalled in the last two minutes"
    },
    {
     "expr": "increase(jvm_classes_loaded_classes{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m]) OR increase(jvm_classes_loaded{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "Class loaded in the last two minutes"
    },
    {
     "expr": "jvm_buffer_count_buffers{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} OR jvm_buffer_count{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"} ",
     "legendFormat": "{{id}} Buffers"
    }
   ]
  },
  {
   "title": "JVM Thread Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\"}",
     "legendFormat": "{{state}} Threads"
    }
   ]
  },
  {
   "title": "Local Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{result=\"hit\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\",namespace=~\"$namespace\"}[2m])) by(name) / sum(rate(cache_gets_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\",namespace=~\"$namespace\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Local Cache Eviction per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_evictions_total{service=\"$appname\",instance=\"$instance\",namespace=~\"$namespace\",name=~\"$localcache\"}[70s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Local Cache Miss per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\",namespace=~\"$namespace\"}[70s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Local Cache Put per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_puts_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\",namespace=~\"$namespace\"}[70s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}