{
 "title": "connection-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "appname",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count,service)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"},pod)"
    }
   },
   {
    "name": "localcache",
    "label": "Local Cache",
    "query": {
     "query": "label_values(cache_size{service=\"$appname\",instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of copies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"$appname\"}"
    }
   ]
  },
  {
   "title": "Application Node and Pod Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=\"$appname\"}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{ pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "HTTP Interface Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP API Request Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Average HTTP API time consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_sum{service=\"$appname\"}[2m])) by (uri) / sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview of traffic of each node component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) ",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_consumed_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} - consumed"
      },
      {
       "expr": "sum(irate(rabbitmq_published_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} - published"
      }
     ]
    },
    {
     "title": "Logback Log",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m]))\n",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Logback Level",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 36 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m])) by (instance,level)",
       "legendFormat": "{{instance}} - {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview of key indicators of each node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "YoungGC Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "times/minute" } },
     "yaxes": [
      { "format": "times/minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",action=~\".*minor.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "New Generation Memory Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OldGC Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "times/minute" } },
     "yaxes": [
      { "format": "times/minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",action=~\".*major.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Old Generation Memory Allocation (Promotion Object)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Maximum Pause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$appname\"} > 0",
       "legendFormat": "{{instance}} - {{cause}}"
      }
     ]
    },
    {
     "title": "Old Generation Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$appname\",id=~\"[a-zA-Z0-9\\\\s]+Old[a-zA-Z0-9\\\\s]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " sum(jvm_memory_used_bytes{service=\"$appname\",area=\"heap\"}) by (instance) / sum(jvm_memory_max_bytes{service=\"$appname\",area=\"heap\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$appname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File descriptors opened by the process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open{service=\"$appname\"} OR process_files_open_files{service=\"$appname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Container OOM/Restart Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=\"$appname\"}",
       "legendFormat": "{{pod}} - OOMKilled"
      },
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"$appname\"}[3m])",
       "legendFormat": "{{pod}} - Restarted in the last 3 minutes"
      }
     ]
    },
    {
     "title": "Tomcat thread pool usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(tomcat_threads_busy{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}/ tomcat_threads_config_max) OR (tomcat_threads_busy_threads{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}/ tomcat_threads_config_max_threads)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat Active Threads",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} OR tomcat_threads_busy_threads{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node JVM Thread Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$appname\"}",
       "legendFormat": "{{instance}} - {{state}} Threads"
      }
     ]
    },
    {
     "title": "Cluster JVM Thread Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_threads_states_threads{service=\"$appname\"}[1m])) by (state)",
       "legendFormat": "{{state}} Threads"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System LoadAvg in the last minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POD CPU usage",
     "type": "graph",
     "description": "Pod CPU usage statistics from k8s",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{container!~\"(POD|istio-proxy)\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m]) ) by (pod) / max( kube_pod_container_resource_limits{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",resource=\"cpu\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD memory usage",
     "type": "graph",
     "description": "Pod memory usage statistics from k8s",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 78 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{ container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ) by (pod)/ max( kube_pod_container_resource_limits{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\",resource=\"memory\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD Network IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[3m])",
       "legendFormat": "{{pod}} - Sent Bytes"
      },
      {
       "expr": "irate(container_network_receive_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[3m])",
       "legendFormat": "{{pod}} - Received Bytes"
      }
     ]
    },
    {
     "title": "POD Disk IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 86 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m])",
       "legendFormat": "{{pod}} - Read Bytes"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m])",
       "legendFormat": "{{pod}} - Write Bytes "
      }
     ]
    },
    {
     "title": "Container CPU Throttled Periods %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m])\n /increase(container_cpu_cfs_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container CPU Throttled Time Per Period",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " irate(container_cpu_cfs_throttled_seconds_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m]) / 10",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Node JVM & Key Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM memory pool maximum configuration",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 21, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}})"
      }
     ]
    },
    {
     "title": "GC Memory Allocation",
     "type": "graph",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "Young Gen bytes added per second"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "Old Gen bytes added per second"
      }
     ]
    },
    {
     "title": "JVM memory pool used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}}) "
      }
     ]
    },
    {
     "title": "GC pause duration",
     "type": "graph",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{action}} ({{cause}}) - Maximum pause duration"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\"}[2m]) / rate(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "{{action}} ({{cause}}) - Average pause"
      }
     ]
    },
    {
     "title": "GC Reasons and Frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "times/minute" } },
     "yaxes": [
      { "format": "times/minute" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[70s])",
       "legendFormat": "{{action}} ({{cause}}) "
      }
     ]
    },
    {
     "title": " Cumulative GC times in the selected period",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause)",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Cumulative GC time consumed in the selected period",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause) ",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Tomcat Thread Pool",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{service=\"$appname\",instance=\"$instance\"} OR tomcat_threads_busy_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Active thread (busy)"
      },
      {
       "expr": "tomcat_threads_config_max{service=\"$appname\",instance=\"$instance\"} OR tomcat_threads_config_max_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Maximum number of threads"
      },
      {
       "expr": "tomcat_threads_current{service=\"$appname\",instance=\"$instance\"} OR tomcat_threads_current_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Current number of threads"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$appname\",instance=\"$instance\"} OR jvm_threads_daemon_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Daemon Threads"
      },
      {
       "expr": "jvm_threads_live{service=\"$appname\",instance=\"$instance\"} OR jvm_threads_live_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Daemon + None Daemon Threads"
      },
      {
       "expr": "jvm_threads_peak{service=\"$appname\",instance=\"$instance\"} OR jvm_threads_peak_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Peak number of threads"
      }
     ]
    },
    {
     "title": "Class loading statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_classes_unloaded_classes_total{service=\"$appname\",instance=\"$instance\"}[2m]) OR increase(jvm_classes_unloaded_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": " Class uninstalled in the last two minutes"
      },
      {
       "expr": "increase(jvm_classes_loaded_classes{service=\"$appname\",instance=\"$instance\"}[2m]) OR increase(jvm_classes_loaded{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "Class loaded in the last two minutes"
      },
      {
       "expr": "jvm_buffer_count_buffers{service=\"$appname\",instance=\"$instance\"} OR jvm_buffer_count{service=\"$appname\",instance=\"$instance\"} ",
       "legendFormat": "{{id}} Buffers"
      }
     ]
    },
    {
     "title": "JVM Thread Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{state}} Threads"
      }
     ]
    },
    {
     "title": "Local Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{result=\"hit\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[2m])) by(name) / sum(rate(cache_gets_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[2m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Local Cache Eviction per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Local Cache Miss per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Local Cache Put per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Redis Command",
     "type": "stat",
     "description": "Redis Commands executed per second by all nodes",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))"
      }
     ]
    },
    {
     "title": "Cluster TCP Connection Statistics",
     "type": "graph",
     "description": " Redis connection pool statistics for all nodes",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "Redis commands executed per second (Borrow)"
      },
      {
       "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "Number of connections returned per second (Return)"
      },
      {
       "expr": "sum(increase(commonspool2_con_created_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "TCP connections created per minute"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "TCP connections destroyed per minute"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "TCP connections destroyed every minute by scheduled tasks"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "TCP connections destroyed every minute triggered by connection acquisition"
      }
     ]
    },
    {
     "title": "Current node connection pool statistics",
     "type": "graph",
     "description": "Redis connection pool usage and configuration for a single node",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"} / commonspool2_con_config_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Usage"
      },
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Current number of active connections"
      },
      {
       "expr": "commonspool2_threads_waits{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - Number of threads blocked waiting when pool is exhausted"
      },
      {
       "expr": "commonspool2_con_idle{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - Current number of idle connections"
      },
      {
       "expr": "commonspool2_con_config_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - Maximum number of connections"
      },
      {
       "expr": "commonspool2_con_config_idle_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - Maximum number of idle connections"
      },
      {
       "expr": "commonspool2_con_config_idle_min{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - Minimum number of idle connections"
      }
     ]
    },
    {
     "title": "Current Node TCP Connection Statistics",
     "type": "graph",
     "description": "TCP connection statistics of a single node in the last minute",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Average time taken by Redis commands [ms]"
      },
      {
       "expr": "irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - Redis commands executed per second (Borrow)"
      },
      {
       "expr": "irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - Number of connections returned per second (Return)"
      },
      {
       "expr": "increase(commonspool2_con_created_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - TCP connections created per minute"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - TCP connections destroyed per minute"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - TCP connection destroyed every minute by a scheduled task"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - TCP connections destroyed every minute triggered by connection acquisition"
      }
     ]
    },
    {
     "title": "Current node connection pool time statistics",
     "type": "graph",
     "description": "Time consumption statistics of Redis connection pool of a single node",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Average time taken by Redis commands"
      },
      {
       "expr": "commonspool2_con_idle_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Average idle time of the connection"
      },
      {
       "expr": "commonspool2_con_wait_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Get the average waiting time for the connection"
      },
      {
       "expr": "commonspool2_con_config_maxwait_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Maximum waiting time configured by the client"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Cache (Caffeine)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Accumulated Cache Eviction of each node in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 86 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Accumulated Cache Miss of each node in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Accumulated Cache Put of each node in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 94 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Accumulated Cache Hit of each node in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 94 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"hit\",service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Local Cache QPS",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_gets_total{service=\"$appname\",name=~\"$localcache\"}[2m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cluster Local Cache Miss per minute",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cluster Local Cache Put per minute",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cluster Local Cache Eviction per minute",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cache size of each node",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_size{service=\"$appname\",name=~\"$localcache\"}",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Cache hit rate of each node",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 124 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{result=\"hit\",service=\"$appname\",name=~\"$localcache\"}[2m])) by (instance,name) / sum(rate(cache_gets_total{service=\"$appname\",name=~\"$localcache\"}[2m])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Local Cache Miss per node per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Local Cache Eviction per minute for each node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Local Cache Put per minute for each node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}