{
 "title": "connection-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "appname",
    "label": "应用",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count,service)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"},pod)"
    }
   },
   {
    "name": "localcache",
    "label": "Local Cache",
    "query": {
     "query": "label_values(cache_size{service=\"$appname\",instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "副本数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"$appname\"}"
    }
   ]
  },
  {
   "title": "应用节点和 Pod Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=\"$appname\"}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{ pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "HTTP接口统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP API 请求量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP API 平均耗时",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_sum{service=\"$appname\"}[2m])) by (uri) / sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "各节点组件流量概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) ",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(http_server_requests_seconds_count{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_consumed_total{service=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - consumed"
      },
      {
       "expr": "sum(irate(rabbitmq_published_total{service=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - published"
      }
     ]
    },
    {
     "title": "Logback 日志",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m]))\n",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Logback  Level ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 36 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{service=\"$appname\"}[2m]))  by (instance,level)",
       "legendFormat": "{{instance}}  - {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "各节点关键指标概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "YoungGC 频率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "次/分钟" } },
     "yaxes": [
      { "format": "次/分钟" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",action=~\".*minor.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "新生代内存分配",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OldGC 频率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "次/分钟" } },
     "yaxes": [
      { "format": "次/分钟" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",action=~\".*major.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "老年代内存分配(晋升对象)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC 最大停顿",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$appname\"} > 0",
       "legendFormat": "{{instance}}  - {{cause}}"
      }
     ]
    },
    {
     "title": "老年代内存",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$appname\",id=~\"[a-zA-Z0-9\\\\s]+Old[a-zA-Z0-9\\\\s]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "堆内存(Heap) 使用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " sum(jvm_memory_used_bytes{service=\"$appname\",area=\"heap\"}) by (instance) /  sum(jvm_memory_max_bytes{service=\"$appname\",area=\"heap\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "进程CPU使用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$appname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "进程打开的文件描述符",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open{service=\"$appname\"} OR process_files_open_files{service=\"$appname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "容器OOM/Restart统计",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=\"$appname\"}",
       "legendFormat": "{{pod}} - OOMKilled"
      },
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"$appname\"}[3m])",
       "legendFormat": "{{pod}} - 近3分钟重启"
      }
     ]
    },
    {
     "title": "Tomcat 线程池使用率",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(tomcat_threads_busy{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}/ tomcat_threads_config_max)  OR  (tomcat_threads_busy_threads{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}/ tomcat_threads_config_max_threads)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat 活跃线程",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} OR tomcat_threads_busy_threads{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "节点 JVM 线程状态",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$appname\"}",
       "legendFormat": "{{instance}} -  {{state}} Threads"
      }
     ]
    },
    {
     "title": "集群 JVM 线程状态",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_threads_states_threads{service=\"$appname\"}[1m])) by (state)",
       "legendFormat": "{{state}} Threads"
      }
     ]
    },
    {
     "title": "进程 CPU 使用率",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "近一分钟 System LoadAvg ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "POD CPU使用率",
     "type": "graph",
     "description": "k8s统计的POD CPU使用率",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{container!~\"(POD|istio-proxy)\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m]) ) by (pod) / max( kube_pod_container_resource_limits_cpu_cores{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD 内存使用率",
     "type": "graph",
     "description": "k8s统计的POD 内存使用率",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 78 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{ container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ) by (pod)/ max( kube_pod_container_resource_limits_memory_bytes{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"} ) by (pod)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "POD 网络IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[3m])",
       "legendFormat": "{{pod}}  -  Sent Bytes"
      },
      {
       "expr": "irate(container_network_receive_bytes_total{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[3m])",
       "legendFormat": "{{pod}}  - Received Bytes"
      }
     ]
    },
    {
     "title": "POD 磁盘IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 86 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m])",
       "legendFormat": "{{pod}} - Read Bytes"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{container=\"$appname\",pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[5m])",
       "legendFormat": "{{pod}} - Write Bytes "
      }
     ]
    },
    {
     "title": "Container CPU Throttled Periods %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m])\n /increase(container_cpu_cfs_periods_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container CPU Throttled Time Per Period",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " irate(container_cpu_cfs_throttled_seconds_total{container=~\"$appname\", pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"}[2m]) / 10",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "当前节点JVM&关键指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM内存池最大配置",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 21, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}})"
      }
     ]
    },
    {
     "title": "GC 内存分配",
     "type": "graph",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "新生代(Young Gen)每秒增加的字节"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "老年代(Old Gen)每秒增加的字节"
      }
     ]
    },
    {
     "title": "已使用的JVM内存池 ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}}) "
      }
     ]
    },
    {
     "title": "GC 停顿时长",
     "type": "graph",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{action}} ({{cause}})  - 最大停顿时长"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\"}[2m]) / rate(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "{{action}} ({{cause}}) - 平均停顿"
      }
     ]
    },
    {
     "title": "GC 原因与频次",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "次/分钟" } },
     "yaxes": [
      { "format": "次/分钟" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[70s])",
       "legendFormat": "{{action}} ({{cause}}) "
      }
     ]
    },
    {
     "title": "所选时段内累计GC次数",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause)",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "所选时段内累计GC耗时",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 45 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_sum{service=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause) ",
       "legendFormat": "{{action}}  ({{cause}})"
      }
     ]
    },
    {
     "title": "Tomcat 线程池",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{service=\"$appname\",instance=\"$instance\"} OR tomcat_threads_busy_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "活跃线程(busy)"
      },
      {
       "expr": "tomcat_threads_config_max{service=\"$appname\",instance=\"$instance\"} OR tomcat_threads_config_max_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "最大线程数"
      },
      {
       "expr": "tomcat_threads_current{service=\"$appname\",instance=\"$instance\"} OR  tomcat_threads_current_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "当前线程数"
      }
     ]
    },
    {
     "title": "JVM 线程",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$appname\",instance=\"$instance\"} OR  jvm_threads_daemon_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Daemon Threads"
      },
      {
       "expr": "jvm_threads_live{service=\"$appname\",instance=\"$instance\"} OR  jvm_threads_live_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Daemon + None Daemon Threads"
      },
      {
       "expr": "jvm_threads_peak{service=\"$appname\",instance=\"$instance\"} OR  jvm_threads_peak_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "峰值线程数"
      }
     ]
    },
    {
     "title": "Class加载统计",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_classes_unloaded_classes_total{service=\"$appname\",instance=\"$instance\"}[2m]) OR increase(jvm_classes_unloaded_total{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟卸载的Class"
      },
      {
       "expr": "increase(jvm_classes_loaded_classes{service=\"$appname\",instance=\"$instance\"}[2m]) OR increase(jvm_classes_loaded{service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟加载的Class"
      },
      {
       "expr": "jvm_buffer_count_buffers{service=\"$appname\",instance=\"$instance\"} OR  jvm_buffer_count{service=\"$appname\",instance=\"$instance\"} ",
       "legendFormat": "{{id}} Buffers"
      }
     ]
    },
    {
     "title": "JVM 线程状态",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{state}} Threads"
      }
     ]
    },
    {
     "title": "Local Cache 命中率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{result=\"hit\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[2m])) by(name) / sum(rate(cache_gets_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[2m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "每分钟 Local Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "每分钟 Local Cache Miss",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "每分钟 Local Cache Put",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",instance=\"$instance\",name=~\"$localcache\"}[70s])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "集群 Redis Command",
     "type": "stat",
     "description": "所有节点每秒执行的Redis Command",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))"
      }
     ]
    },
    {
     "title": "集群TCP连接统计",
     "type": "graph",
     "description": "所有节点的Redis 连接池统计",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "每秒执行的Redis命令(Borrow)"
      },
      {
       "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\"}[2m]))",
       "legendFormat": "每秒归还连接的次数(Return)"
      },
      {
       "expr": "sum(increase(commonspool2_con_created_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "每分钟创建的TCP连接"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "每分钟销毁的TCP连接"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "每分钟由定时任务触发销毁的TCP连接"
      },
      {
       "expr": "sum(increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
       "legendFormat": "每分钟由获取连接触发销毁的TCP连接"
      }
     ]
    },
    {
     "title": "当前节点连接池统计",
     "type": "graph",
     "description": "单个节点的 Redis 连接池使用率和配置",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"} / commonspool2_con_config_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 使用率"
      },
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}}  - 当前活跃的连接数"
      },
      {
       "expr": "commonspool2_threads_waits{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 池耗尽时阻塞等待的线程数"
      },
      {
       "expr": "commonspool2_con_idle{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 当前的空闲连接数"
      },
      {
       "expr": "commonspool2_con_config_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最大连接数"
      },
      {
       "expr": "commonspool2_con_config_idle_max{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最大空闲连接数"
      },
      {
       "expr": "commonspool2_con_config_idle_min{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最小空闲连接数"
      }
     ]
    },
    {
     "title": "当前节点TCP连接统计",
     "type": "graph",
     "description": "单个节点最近一分钟的TCP连接统计",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Redis命令的平均耗时[ms]"
      },
      {
       "expr": "irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - 每秒执行的Redis命令(Borrow)"
      },
      {
       "expr": "irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - 每秒归还连接的次数(Return)"
      },
      {
       "expr": "increase(commonspool2_con_created_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}}  - 每分钟创建的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟销毁的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟由定时任务触发销毁的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟由获取连接触发销毁的TCP连接"
      }
     ]
    },
    {
     "title": "当前节点连接池耗时统计",
     "type": "graph",
     "description": "单个节点的Redis连接池耗时统计",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Redis命令的平均耗时"
      },
      {
       "expr": "commonspool2_con_idle_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 连接的平均闲置时长"
      },
      {
       "expr": "commonspool2_con_wait_meantime_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 获取连接的平均等待时长"
      },
      {
       "expr": "commonspool2_con_config_maxwait_mseconds{comp_type=~\"redis.+\",service=\"$appname\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 客户端配置的最大等待时长"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Cache (Caffeine)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内各节点累计Cache Eviction",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内各节点累计Cache Miss",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内各节点累计Cache Put",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内各节点累计Cache Hit",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"hit\",service=\"$appname\",name=~\"$localcache\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "集群 Local Cache QPS",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_gets_total{service=\"$appname\",name=~\"$localcache\"}[2m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "集群每分钟 Local Cache Miss ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "集群每分钟  Local Cache Put",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "集群每分钟 Local Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "各节点缓存大小",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_size{service=\"$appname\",name=~\"$localcache\"}",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "各节点缓存命中率",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{result=\"hit\",service=\"$appname\",name=~\"$localcache\"}[2m])) by(instance,name) / sum(rate(cache_gets_total{service=\"$appname\",name=~\"$localcache\"}[2m])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "各节点每分钟 Local Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "各节点每分钟 Local Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "各节点每分钟 Local Cache Put",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{service=\"$appname\",name=~\"$localcache\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}