{
 "title": "gateway-service-api",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Gateway Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appname", "label": "Gateway", "query": "infra-gateway" },
   {
    "name": "backend",
    "label": "Service provider (support sug)",
    "query": {
     "query": "label_values(connectionpool_request_total{app=\"$appname\",envtype=\"$envtype\"},id)"
    }
   },
   {
    "name": "api",
    "label": "Interface",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"},request)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface caller QPS trend",
   "type": "graph",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",request=~\"$api\",group=~\"$backend\"}[2m])) by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Slowest Interface Ranking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces with a time consumption greater than 500ms in the selected period (ranked by number)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"0.5\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request)) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TOP 20 API Request Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": " TOP 20 interfaces with the highest number of requests in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "topk(20,(sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request)) > 0)",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface 5xx / 4xx Ranking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface 5xx statistics in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 19 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Interface 4xx statistics in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 28 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  }
 ]
}