{
 "title": "gateway-overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appname", "label": "网关", "query": "infra-gateway" }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[2m]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "当前并发",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_http_requests_current{app=\"$appname\",envtype=\"$envtype\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "应用节点",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "instance_health_status{app=\"$appname\",envtype=~\"$envtype\"}"
    }
   ]
  },
  {
   "title": "Error日志(每分钟)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase({compType=\"logging\",level=\"error\",app=\"$appname\",envtype=\"$envtype\"}[1m]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "5xx请求数占比(每分钟)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\"}[70s])) / sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[70s]))) >=0 OR on() vector(0)"
    }
   ]
  },
  {
   "title": "HTTP QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_total{status=~\"2..\",app=\"$appname\",envtype=\"$envtype\"}[2m])) OR on() vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\"}[2m])) OR on() vector(0)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\"}[2m])) OR on() vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"3..\",app=\"$appname\",envtype=\"$envtype\"}[2m])) OR on() vector(0)",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[2m])) by (app_cluster)",
     "legendFormat": "{{app_cluster}}"
    },
    {
     "expr": "sum(server_connections_current_total{app=\"$appname\",envtype=\"$envtype\"})",
     "legendFormat": "TCP并发数"
    }
   ]
  },
  {
   "title": "5xx的API接口 [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (group,request) > 0",
     "legendFormat": "{{group}} - {{request}}"
    }
   ]
  },
  {
   "title": "节点概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP接口QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RPC调用QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM线程数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_threads{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "当前打开的文件描述符",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "内存使用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " instance_mem_free_bytes{app=\"$appname\",envtype=\"$envtype\"}\n    / instance_mem_total_bytes\n  \n",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "近两分钟CPU Throttle 次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(node_cgroup_cpu_throttled_total{app=\"$appname\",envtype=\"$envtype\"}[2m])",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "进程内存(WSS)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_cgroup_memory_usage_bytes{app=\"$appname\",envtype=~\"$envtype\"}-node_cgroup_memory_inactive_file_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Log4j RingBuffer Remain",
     "type": "graph",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "log4j_asynclogger_ringbuffer_remain{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Netty Server 统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "最大TCP连接数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "server_config_connection_max{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "IO线程数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "server_config_threads_io{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "当前已用的Direct Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zuul_directmemory_reserved_bytes_total{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} "
      }
     ]
    },
    {
     "title": "EventLoop TCP + HTTP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "server_eventloop_connections_current{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}}  EventLoop-{{eventloop}}  当前TCP连接 "
      },
      {
       "expr": "server_eventloop_http_requests_current{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}}  EventLoop-{{eventloop}}  当前HTTP Request "
      }
     ]
    },
    {
     "title": "Netty Server TCP连接数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "server_connections_current_total{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "后端服务TCP创建失败 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(connectionpool_create_fail_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "TCP By Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(server_connections_current_total{app=\"$appname\",envtype=\"$envtype\"}) by (app_cluster)",
       "legendFormat": "网关当前TCP并发 - {{app_cluster}}"
      },
      {
       "expr": "sum(server_eventloop_http_requests_current{app=\"$appname\",envtype=\"$envtype\"}) by (app_cluster)",
       "legendFormat": "网关EventLoop当前HttpRequest - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(connectionpool_create_fail_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "后端服务创建失败的TCP [ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(server_connections_errors_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "网关链路异常的TCP [ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(server_connections_idle_timeout_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "网关闲置超时的TCP [ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(server_connections_connect_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "网关已创建的TCP[ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(server_connections_close_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "网关已关闭的TCP[ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(connectionpool_create_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "后端服务已创建的TCP[ 1m ] - {{app_cluster}}"
      },
      {
       "expr": "sum(increase(connectionpool_close_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster)",
       "legendFormat": "后端服务已关闭的TCP[ 1m ] - {{app_cluster}}"
      }
     ]
    },
    {
     "title": "内部业务监控 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oauth_accesstoken_fallback_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) ",
       "legendFormat": "获取AccessToken触发Fallback次数"
      },
      {
       "expr": "sum(increase(oauth_ratelimiter_fallback_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) ",
       "legendFormat": "限流检查触发Fallback次数"
      },
      {
       "expr": "sum(increase(oauth_accesstoken_create_fallback{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) ",
       "legendFormat": "创建AccessToken触发fallback的次数"
      },
      {
       "expr": "sum(increase(zuul_no_retry_total{app=\"$appname\",envtype=\"$envtype\",id=\"incomplete_body\"}[1m])) by (app) ",
       "legendFormat": "无法重试因为没有Buffer RequestBody"
      },
      {
       "expr": "sum(increase(server_http_request_read_timeout_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) ",
       "legendFormat": "客户端请求读取超时的次数"
      },
      {
       "expr": "sum(increase(login_session_failed_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app_cluster,app) ",
       "legendFormat": "登录Token校验失败(超时或队列满了) [ {{app_cluster}} ]"
      }
     ]
    },
    {
     "title": "内存泄露检测",
     "type": "graph",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "NettyLeakDetector{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}} traced leak + untraced leak (gc) - {{id}}"
      },
      {
       "expr": "NettyLeakDetector_instances{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": " {{instance}}  instance leak - {{id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "服务提供方统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "服务维度QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[2m])) by (group)  > 0",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "近一分钟错误码趋势",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_errorcode_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (server,code)> 0",
       "legendFormat": "{{code}} - {{server}}"
      }
     ]
    },
    {
     "title": "触发单节点最大并发限制的后端服务 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(zuul_origin_rejected_requests_total{app=\"$appname\",envtype=\"$envtype\"}[70s]) > 0",
       "legendFormat": "{{id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "触发断路器的API接口",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\"} == 1",
       "legendFormat": "{{instance}}  [ {{group}} ] {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "网关客户端统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "近1分钟客户端错误码趋势",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oauthclient_errorcode_total{app=\"$appname\",envtype=\"$envtype\"}[65s])) by (client,code) > 0",
       "legendFormat": " {{client}} - {{code}} "
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\"}[2m])) by (client)  > 0",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "OAuth Client 触发限流的API接口 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(oauthclient_ratelimit_triggered_total{app=\"$appname\",envtype=\"$envtype\"}[70s]) > 0",
       "legendFormat": "{{client}} - [ {{group}} ] {{name}} "
      }
     ]
    },
    {
     "title": "OAuth Client 5xx的API接口 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oauthclient_http_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\"}[70s])) by (client,group,name) > 0",
       "legendFormat": "[ {{client}} - {{group}}  ]  {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM GC/Redis/日志概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "日志统计[每分钟]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{app=\"$appname\",envtype=~\"$envtype\"}[65s]) OR increase(log4j2_events_total{app=\"$appname\",envtype=~\"$envtype\"}[65s])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Error日志统计[每分钟]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{level=\"error\",app=\"$appname\",envtype=~\"$envtype\"}[65s]) OR increase(log4j2_events_total{level=\"error\",app=\"$appname\",envtype=~\"$envtype\"}[65s])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "JVM GC [每分钟]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(instance_gc_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}[1m])",
       "legendFormat": "{{name}} - {{instance}} "
      }
     ]
    },
    {
     "title": "JVM GC 平均耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance_gc_duration_seconds_sum / instance_gc_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": "{{name}} - {{instance}} "
      }
     ]
    },
    {
     "title": "JVM 老年代内存",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"$appname\",envtype=~\"$envtype\",id=~\"[a-zA-Z0-9\\\\s]+Old[a-zA-Z0-9\\\\s]+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Http Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_bytes_sum{app=\"$appname\",envtype=\"$envtype\"}[2m]))",
       "legendFormat": "每秒接收的字节"
      },
      {
       "expr": "sum(irate(http_server_response_bytes_sum{app=\"$appname\",envtype=\"$envtype\"}[2m]))",
       "legendFormat": "每秒发送的字节"
      }
     ]
    },
    {
     "title": "Redis  Command QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[2m])",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Redis  Command 耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}  - {{comp_name}}"
      }
     ]
    }
   ]
  }
 ]
}