{
 "title": "gateway-backend-overview",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "网关环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appname", "label": "网关", "query": "infra-gateway" },
   {
    "name": "backend",
    "label": "服务提供方( 支持sug )",
    "query": {
     "query": "label_values(connectionpool_request_total{app=\"$appname\",envtype=\"$envtype\"},id)"
    }
   },
   {
    "name": "gwclient",
    "label": "网关客户端",
    "query": {
     "query": "label_values(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"},client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP 接口",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\"}[2m]))"
    }
   ]
  },
  {
   "title": "HTTP QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_total{status=~\"2..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[2m])) by (app_cluster)",
     "legendFormat": "{{app_cluster}}"
    }
   ]
  },
  {
   "title": "近一分钟5xx占比",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[1m])) / sum(increase(http_server_request_total{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[1m]))) >= 0 OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_request_bytes_sum{app=\"$appname\",envtype=\"$envtype\",compName=~\"$backend\"}[3m])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "近一分钟全局错误码",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_errorcode_total{app=\"$appname\",envtype=\"$envtype\",server=\"$backend\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_response_bytes_sum{app=\"$appname\",envtype=\"$envtype\",compName=~\"$backend\"}[3m])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "客户端调用统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用方QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[2m])) by (client)  > 0",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "$gwclient",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 19 },
     "repeat": "gwclient",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{client=~\"$gwclient\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "$gwclient",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{client=~\"$gwclient\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) OR on() vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "接口请求量Top20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内请求量TOP 20 接口",
     "type": "graph",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,(sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request)) > 0)",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "慢接口排行",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内耗时大于500ms的接口 ( 按次数排行 ）",
     "type": "graph",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"0.5\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request)) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口 5xx / 4xx 排行",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内接口5xx统计",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "所选时段内接口4xx统计",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 25 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"}[$__range])) by (request) > 0",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口熔断统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "断路器熔断开启(OPEN)的接口",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 17 },
     "repeat": "request",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"} == 1 or resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"} == 4",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "断路器半开状态(HALF_OPEN)的接口",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"} == 2",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "断路器失败请求比例大于0的接口",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate{app=\"$appname\",envtype=\"$envtype\",group=\"$backend\"} > 0",
       "legendFormat": "{{instance}}  - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP接口IO统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP IO",
     "type": "graph",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_bytes_sum{app=\"$appname\",envtype=\"$envtype\",server=~\"$backend\"}[3m])) OR on() vector(0)",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "sum(irate(http_server_response_bytes_sum{app=\"$appname\",envtype=\"$envtype\",server=~\"$backend\"}[3m])) OR on() vector(0)",
       "legendFormat": "Sent Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "服务TCP连接池统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP连接并发数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zuul_origin_concurrent_requests{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "近一分钟TCP连接池统计",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(connectionpool_inactive_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "TCP链路 Inactive"
      },
      {
       "expr": "sum(increase(connectionpool_idle_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "TCP链路 Idle"
      },
      {
       "expr": "sum(increase(connectionpool_error_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "TCP链路 Exception Caught"
      },
      {
       "expr": "sum(increase(zuul_origin_rejected_requests_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "触发MaxConcurrentRequestExceeded的次数"
      },
      {
       "expr": "sum(increase(connectionpool_maxConnsPerHostExceeded_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "触发MaxConnectionPerHostExceeded的次数"
      },
      {
       "expr": "sum(increase(connectionpool_request_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "向连接池获取TCP连接的次数"
      },
      {
       "expr": "sum(increase(connectionpool_reuse_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "TCP连接复用的次数"
      },
      {
       "expr": "sum(increase(connectionpool_create_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "新创建的TCP连接"
      },
      {
       "expr": "sum(increase(connectionpool_create_success_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "成功创建的TCP连接"
      },
      {
       "expr": "sum(increase(connectionpool_create_fail_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "创建失败的TCP连接"
      },
      {
       "expr": "sum(connectionpool_inPool{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"})",
       "legendFormat": "当前尚在池里的TCP连接数"
      },
      {
       "expr": "sum(connectionpool_inUse{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"})",
       "legendFormat": "当前池里已被占用的TCP连接数"
      },
      {
       "expr": "sum(increase(connectionpool_fromPoolIsClosed_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "从池里Borrow时已Close的TCP连接"
      },
      {
       "expr": "sum(increase(connectionpool_release_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "Release到池里的次数"
      },
      {
       "expr": "sum(increase(connectionpool_alreadyClosed_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "Release到池里时TCP连接已Close的次数"
      },
      {
       "expr": "sum(increase(connectionpool_close_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "已关闭的TCP连接"
      },
      {
       "expr": "sum(increase(connectionpool_closeWrtBusyConnCounter_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}[1m]))",
       "legendFormat": "因尚未Write Ready但放回池中被关闭的TCP连接"
      }
     ]
    }
   ]
  },
  {
   "title": "服务TCP连接创建耗时",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内TCP创建耗时直方图",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00([0-3][0-F]|4[0-6])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "<=109us"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(4[7-D])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "262us"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T004E|T004F|T0050\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "524us"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T0051|T0052|T0053\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "786us"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T0054|T0055|T0056\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T0057|T0058|T0059\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "2.1ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(5[A-F])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "4.1ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T0060|T0061|T0062\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "8.3ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(6[3-F])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "55.9ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(7[0-F])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "715ms"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(8[0-3])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "1.073s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(8[4-6])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "2.147s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(8[7-9])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "3.221s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00(8[A-C])\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "4.294s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=\"T008D\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "5.726s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=\"T008E\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "7.158s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=\"T008F\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": "8.589s"
      },
      {
       "expr": "sum(increase(connectionpool_createTiming_total{app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\",percentile=~\"T00[9-F][0-F]\",statistic=\"percentile\"}[$__interval]))OR on() vector(0)",
       "legendFormat": ">8.589s"
      }
     ]
    },
    {
     "title": "TCP创建耗时百分比 - 长尾请求",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 95%的TCP创建耗时 "
      },
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 99%的TCP创建耗时 "
      }
     ]
    },
    {
     "title": "TCP创建耗时百分比",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 25%的TCP创建耗时 "
      },
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 50%的TCP创建耗时 "
      },
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 75%的TCP创建耗时 "
      },
      {
       "expr": "connectionpool_createTiming_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",id=~\"$backend\"}",
       "legendFormat": "{{instance}} - 90%的TCP创建耗时 "
      }
     ]
    }
   ]
  },
  {
   "title": "网关HTTP转发耗时",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "HttpReqest 转发耗时",
     "type": "graph",
     "description": "从接收到客户端 Request Headers 到 Request 全部写入到后端Socket的耗时统计",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25%请求路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50%请求路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75%请求路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90%请求路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95%请求路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_req_routelag_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99%请求路由耗时 - {{instance}}"
      }
     ]
    },
    {
     "title": "HttpResponse 转发耗时",
     "type": "graph",
     "description": "从接收到后端的Response Headers 到  Response 全部写入客户端Socket的耗时统计",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25% Response路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50% Response路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75% Response路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90% Response路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95% Response路由耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_resp_routelag_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99% Response路由耗时 -- {{instance}}"
      }
     ]
    },
    {
     "title": "网关业务逻辑 [ InboundFilter ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_infilter_lag_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99%请求的执行耗时 - {{instance}}"
      }
     ]
    },
    {
     "title": "网关业务逻辑 [ OutboundFilter ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95%请求的执行耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_outfilter_lag_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99%请求的执行耗时 - {{instance}}"
      }
     ]
    },
    {
     "title": "Client RequestBody",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_client_reqbody_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99%请求的读取耗时 - {{instance}}"
      }
     ]
    },
    {
     "title": "后端服务 ResponseBody",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_origin_respbody_seconds{quantile=\"0.25\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "25%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_origin_respbody_seconds{quantile=\"0.5\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "50%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_origin_respbody_seconds{quantile=\"0.75\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "75%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_origin_respbody_seconds{quantile=\"0.9\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "90%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_origin_reqbody_seconds{quantile=\"0.95\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "95%请求的读取耗时 - {{instance}}"
      },
      {
       "expr": "service_passport_origin_respbody_seconds{quantile=\"0.99\",app=\"$appname\",envtype=\"$envtype\",name=~\"$backend\"}",
       "legendFormat": "99%请求的读取耗时 - {{instance}}"
      }
     ]
    },
    {
     "title": "TCP连接获取耗时",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.25\",name=~\"$backend\"}",
       "legendFormat": "{{instance}} - 25%请求获取TCP连接的耗时"
      },
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.5\",name=~\"$backend\"}",
       "legendFormat": "{{instance}} - 50%请求获取TCP连接的耗时"
      },
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.75\",name=~\"$backend\"}",
       "legendFormat": "{{instance}} - 75%请求获取TCP连接的耗时"
      },
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.9\",compName=~\"$backend\"}",
       "legendFormat": "{{instance}} - 90%请求获取TCP连接的耗时"
      },
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.95\",compName=~\"$backend\"}",
       "legendFormat": "{{instance}} - 95%请求获取TCP连接的耗时"
      },
      {
       "expr": "service_passport_con_lag_seconds{quantile=\"0.99\",compName=~\"$backend\"}",
       "legendFormat": "{{instance}} - 99%请求获取TCP连接的耗时"
      }
     ]
    }
   ]
  }
 ]
}