{
 "title": "gateway-client-overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Gateway Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appname", "label": "Gateway", "query": "infra-gateway" },
   {
    "name": "gwclient",
    "label": "Client (Caller)",
    "query": {
     "query": "label_values(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\"},client)"
    }
   },
   {
    "name": "backend",
    "label": "Service Provider",
    "query": {
     "query": "label_values(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",client=~\"$gwclient\"},group)"
    }
   },
   {
    "name": "request",
    "label": "Backend interface",
    "query": {
     "query": "label_values(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",client=~\"$gwclient\"},request)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Error Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global error code trend in the last minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oauthclient_errorcode_total{app=\"$appname\",envtype=\"$envtype\",client=\"$gwclient\"}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Current Limit Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface that triggers current limiting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(oauthclient_ratelimit_triggered_total{app=\"$appname\",envtype=\"$envtype\",client=\"$gwclient\"}[$__interval])) by(group,request)",
       "legendFormat": "{{group}} - {{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface 5xx / 4xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Overview",
     "type": "graph",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",client=\"$gwclient\"}[2m]))",
       "legendFormat": "all"
      },
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"5..\",client=\"$gwclient\"}[2m]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"4..\",client=\"$gwclient\"}[2m]))",
       "legendFormat": "4xx"
      }
     ]
    },
    {
     "title": "HTTP 5xx interface",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"5..\",client=\"$gwclient\"}[2m])) by(group,request) > 0",
       "legendFormat": "{{group}} - {{request}}"
      }
     ]
    },
    {
     "title": "HTTP 4xx interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"4..\",client=\"$gwclient\"}[2m])) by(group,request) > 0",
       "legendFormat": "{{group}} - {{request}} "
      }
     ]
    }
   ]
  },
  { "title": "$backend - $request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "request" },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "repeat": "backend",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",client=\"$gwclient\",name=\"$request\",group=\"$backend\"}[2m])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Interface request volume trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"2..\",client=\"$gwclient\",request=\"$request\",group=~\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": " 2xx"
    },
    {
     "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"5..\",client=\"$gwclient\",request=\"$request\",group=~\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(oauthclient_http_request_total{app=\"$appname\",envtype=\"$envtype\",status=~\"4..\",client=\"$gwclient\",request=\"$request\",group=~\"$backend\"}[2m])) OR on() vector(0)",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "5xx percentage in the last minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "repeat": "backend",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(oauthclient_http_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",client=\"$gwclient\",group=\"$backend\"}[1m])) / sum(increase(oauthclient_http_request_total{app=\"$appname\",client=\"$gwclient\",group=\"$backend\"}[1m]))) >= 0 OR on() vector(0)"
    }
   ]
  }
 ]
}