{
 "title": "app-circuitbreaker",
 "time": { "from": "2022-12-07T00:00:00.000Z", "to": "2022-12-07T05:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "Application (support sug)",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "group",
    "label": "Request Grouping",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\"},group)"
    }
   },
   {
    "name": "method",
    "label": "Fuse",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\",group=~\"$group\"},name)"
    }
   },
   {
    "name": "instance",
    "label": " Node",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface with fuse open (OPEN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fuse OPEN interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"} == 1 or resilience4j_circuitbreaker_state{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"} == 4",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Single Circuit Breaker Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$method",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}"
    }
   ]
  },
  {
   "title": " 0=Closed , 1=Open , 2=Half Open , 3=Disabled , 4=Force Open",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Circuit breaker statistics: $method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Failure rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failed{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": " Number of requests that have been fused (not permitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_not_permitted{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Total number of requests (buffered)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Number of failed requests (failed)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failed{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",name=~\"$method\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  }
 ]
}