{
 "title": "http-api-sla",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "Application (support sug)",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "backend",
    "label": "Interface Grouping",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},group)"
    }
   },
   {
    "name": "method",
    "label": "Interface",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\"},request)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface time consumption quantile line",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Horizontal comparison of long-tail requests of interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95(95%) time consumption",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{quantile=\"0.95\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "P99(99%) time consumption",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{quantile=\"0.99\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "P999(99.9%) time consuming",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{quantile=\"0.999\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP status code statistics for the selected period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "5xx Node Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_requests_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",request=\"$method\"}[$__range])) by (instance)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "4xx Node Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_requests_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",request=\"$method\"}[$__range])) by (instance)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "HTTP Status Code Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{request=\"$method\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "HTTP request volume distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_duration_seconds_count{request=\"$method\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Interface: $method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "method" },
  {
   "title": "Request volume trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_total{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) by (app_cluster)",
     "legendFormat": "Cluster: {{app_cluster}} "
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"4..\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) by (instance) > 0",
     "legendFormat": "{{instance}} - 4xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"5..\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) by (instance) > 0",
     "legendFormat": "{{instance}} - 5xx"
    },
    {
     "expr": "sum(irate(http_server_request_total{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time consumption histogram in the selected period",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_bucket{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}