{
 "title": "http-api-index",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "api",
    "label": "HTTP接口",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},request)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总体访问情况",
   "type": "graph",
   "description": "最近一分钟接口访问量趋势",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(increase(http_server_request_total{status=~\"2..\",app=\"$appname\",envtype=\"$envtype\"}[1m])) ",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\"}[1m])) ",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\"}[1m])) ",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(http_server_request_total{status=~\"3..\",app=\"$appname\",envtype=\"$envtype\"}[1m])) ",
     "legendFormat": "3xx"
    },
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) - sum(increase(http_server_request_duration_seconds_bucket{le=\"3.0\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app)) ",
     "legendFormat": "慢请求(>3s)"
    }
   ]
  },
  {
   "title": "请求量(By Api)",
   "type": "graph",
   "description": "最近一分钟接口的请求量趋势",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "请求量(By ServerIP)",
   "type": "graph",
   "description": "最近一分钟接口的请求量",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fail数量(By Api)",
   "type": "graph",
   "description": "最近一分钟接口4xx+5xx的数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"4..|5..\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request))  > 0",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "fail数量(By ServerIp)",
   "type": "graph",
   "description": "最近一分钟接口4xx+5xx的数量",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"4..|5..\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (instance))  > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "平均耗时(By Api)",
   "type": "graph",
   "description": "最近一分钟接口平均耗时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "( sum(increase(http_server_request_duration_seconds_sum{app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request)\n/\nsum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request) ) ",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "API业务码(By Code)",
   "type": "graph",
   "description": "最近一分钟API业务码的数量",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_errorcode_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "3秒以上慢请求(By Api)",
   "type": "graph",
   "description": "最近一分钟慢请求的数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"3.0\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (request)) > 0",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "3秒以上慢请求(By ServerIp)",
   "type": "graph",
   "description": "最近一分钟慢请求数量的趋势",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (instance) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"3.0\",app=\"$appname\",envtype=\"$envtype\",request=~\"$api\"}[1m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Exception ( by Class)",
   "type": "graph",
   "description": "最近一分钟Exception的数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_exception_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (class)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "API Exception ( by ServerIp)",
   "type": "graph",
   "description": "最近一分钟Exception的数量",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_exception_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API数据明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "TODO",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 49 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}