{
 "title": "http-api-overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "慢接口统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "近一分钟慢接口趋势  (点击查看更多统计)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m]))"
      }
     ]
    },
    {
     "title": "所选时段内慢接口节点分布 ( 耗时> 1s )",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance) - sum(increase(http_server_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance)) >= 1",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内慢请求次数 ( 耗时> 2s )",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (request) - \nsum(increase(http_server_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (request)) >= 1",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP状态码/异常统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内HTTP状态码统计",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_server_request_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "所选时段内接口请求量 TOP 20 ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "topk(20,(sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (request)) > 0)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "所选时段内 HTTP 5xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 HTTP 4xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 10, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 Exception 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 Exception 类型分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 10, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_server_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (class)) > 0",
       "legendFormat": "{{class}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP接口概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "HTTP 接口",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[2m]))) OR on() vector(0)",
     "legendFormat": "点击查看接口维度统计"
    }
   ]
  },
  {
   "title": "请求量趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by(app_cluster) ",
     "legendFormat": "集群: {{app_cluster}} "
    },
    {
     "expr": "sum(irate(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by(instance) > 0",
     "legendFormat": "{{instance}} - 5xx"
    },
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by(instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5xx请求占比 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"5..\",group!~\"OperationHandler|default\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[70s])) / sum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[70s]))) >=0 OR on() vector(0)",
     "legendFormat": "查看单个接口的调用统计"
    }
   ]
  },
  {
   "title": "接口请求量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (request) > 0",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "接口平均耗时",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "( sum(increase(http_server_request_duration_seconds_sum{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (request)\n/\nsum(increase(http_server_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (request) ) ",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "近一分钟接口5xx趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (request) ",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "所选时段内5xx接口分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 19, "x": 1, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (request) > 0",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "近一分钟接口业务码趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_errorcode_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "所选时段内接口业务码分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_errorcode_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "近两分钟接口Exception 趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "所选时段内4xx接口分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (request) > 0",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}