{
 "title": "http-slow-api",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "le",
    "label": "耗时(秒)大于",
    "query": "\"0.1\",\"0.3\",\"0.5\",\"1.0\",\"2.0\",\"3.0\",\"5.0\""
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "所选时段内慢接口统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "慢接口(>$le秒)的节点分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance) - sum(increase(http_server_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance)) >= 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "慢接口(>$le秒)的集群分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (app_cluster) - sum(increase(http_server_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (app_cluster)) >= 1",
     "legendFormat": "{{app_cluster}}"
    }
   ]
  },
  {
   "title": "所选时段内慢接口(>$le秒)分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (request) - sum(increase(http_server_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (request)) >= 1",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "近两分钟慢接口(>$le秒)趋势",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (request) - sum(increase(http_server_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (request)) >= 1",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}