{
 "title": "hhub-api-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Envtype",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   { "name": "appGroup", "label": "Product Line", "query": "hhub" },
   {
    "name": "appname",
    "label": "Application",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_group=~\"$appGroup\",envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http Request Per Second by app",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{app=~\"$appname\",app_group=~\"$appGroup\",envtype=~\"$envtype\"}[3m])) by (app)",
     "legendFormat": "{{appname}}"
    }
   ]
  },
  {
   "title": "Non-2xx Http Request Per Minute by app",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{status=~\"5..|4..\",app=~\"$appname\",app_group=~\"$appGroup\",envtype=~\"$envtype\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "hhub-order reservation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "reservation request per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_request_total{request=\"POST /reservation/book\",app=\"hhub-order\",envtype=\"$envtype\"}[1m]))",
     "legendFormat": "/reservation/book"
    },
    {
     "expr": "sum(increase(http_server_request_total{request=\"POST /reservation/book\",app=\"hhub-order\",envtype=\"$envtype\"}[1m] offset 7d))",
     "legendFormat": "/reservation/book - 7d"
    },
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\"}[1m]))",
     "legendFormat": "reservation - total"
    },
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode !=\"success\"}[1m]))",
     "legendFormat": "reservation-failure"
    }
   ]
  },
  {
   "title": "reservation failure by bizcode [ 1m ]",
   "type": "graph",
   "description": "Number of failed reservation by bizcode in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode !=\"success\"}[1m])) by (bizcode)",
     "legendFormat": "{{bizcode}}"
    }
   ]
  },
  {
   "title": "reservation success by channel [ 1m ]",
   "type": "graph",
   "description": "Number of success reservation by channel in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode =\"success\"}[1m])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "reservation failure by channel [ 1m ]",
   "type": "graph",
   "description": "Number of failed reservation by channel in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode !=\"success\"}[1m])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Distribution of reservation failure by bizcode",
   "type": "grafana-piechart-panel",
   "description": "Distribution of reservation failure by bizcode in the selected period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode !=\"success\"}[$__range])) by (bizcode) > 0",
     "legendFormat": "{{bizcode}}"
    }
   ]
  },
  {
   "title": "Distribution of reservation failure by channel",
   "type": "grafana-piechart-panel",
   "description": "Distribution of channel reservation failure in the selected period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crs_order_total{app=\"hhub-order\",envtype=\"$envtype\",bizcode !=\"success\"}[$__range])) by (channel) > 0",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "hhub-distr reservation ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "reservation success by distributor [ 1m ]",
   "type": "graph",
   "description": "Number of success reservation (/reservation/book) by distributor in the last minute ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",function=\"/reservation/book\",bizcode =\"success\"}[1m])) by (distributor)",
     "legendFormat": "{{distributor}}"
    }
   ]
  },
  {
   "title": "reservation failure by distributor [ 1m ]",
   "type": "graph",
   "description": "Number of failed reservation (/reservation/book) by distributor in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",function=\"/reservation/book\",bizcode !=\"success\"}[1m])) by (distributor,bizcode)",
     "legendFormat": "{{distributor}} - {{bizcode}}"
    }
   ]
  },
  {
   "title": "live check success by distributor [ 1m ]",
   "type": "graph",
   "description": "Number of success reservation (/reservation/prebook) by distributor in the last minute ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",function=\"/reservation/prebook\",bizcode =\"success\"}[1m])) by (distributor)",
     "legendFormat": "{{distributor}}"
    }
   ]
  },
  {
   "title": "live check failure by distributor [ 1m ]",
   "type": "graph",
   "description": "Number of failed reservation (/reservation/prebook) by distributor in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",function=\"/reservation/prebook\",bizcode !=\"success\"}[1m])) by (distributor,bizcode)",
     "legendFormat": "{{distributor}} - {{bizcode}}"
    }
   ]
  },
  {
   "title": "Distribution of reservation failure by bizcode",
   "type": "grafana-piechart-panel",
   "description": "Distribution of reservation failure by bizcode in the selected period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",bizcode !=\"success\"}[$__range])) by (bizcode) > 0",
     "legendFormat": "{{bizcode}}"
    }
   ]
  },
  {
   "title": "Distribution of reservation failure by distributor",
   "type": "grafana-piechart-panel",
   "description": "Distribution of distributor reservation failure in the selected period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crs_distr_total{app=\"hhub-distr\",envtype=\"$envtype\",bizcode !=\"success\"}[$__range])) by (distributor) > 0",
     "legendFormat": "{{distributor}}"
    }
   ]
  }
 ]
}