{
 "title": "measured-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "method",
    "label": "Java Method",
    "query": {
     "query": "label_values(services_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},name)"
    }
   },
   {
    "name": "le",
    "label": "慢请求(秒)",
    "query": "\"0.1\",\"0.3\",\"0.5\",\"1.0\",\"2.0\",\"3.0\",\"5.0\""
   }
  ]
 },
 "panels": [
  {
   "title": "总体调用情况 [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(services_req_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(increase(services_req_error_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) ",
     "legendFormat": "Exception"
    },
    {
     "expr": "(sum(increase(services_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app) - sum(increase(services_req_duration_seconds_bucket{le=\"3.0\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (app)) ",
     "legendFormat": "慢请求(>3s)"
    },
    {
     "expr": "sum(increase(services_req_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\"}[1m])) by(app_cluster)",
     "legendFormat": "集群：{{app_cluster}}"
    }
   ]
  },
  {
   "title": "请求量(By Method)  [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(services_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",name=~\"$method\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "请求量(By Instance) [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(services_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",name=~\"$method\"}[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "平均耗时(By Method)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "( sum(increase(services_req_duration_seconds_sum{app=\"$appname\",envtype=\"$envtype\",name=~\"$method\"}[1m])) by (name)\n/\nsum(increase(services_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",name=~\"$method\"}[1m])) by (name) ) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Exception数量(By Method) [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(services_req_error_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$method\"}[1m])) by (name))  > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Exception数量 ( by Class) [ 1m ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(services_req_error_total{app=\"$appname\",envtype=\"$envtype\"}[1m])) by (exception)",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "近一分钟慢请求(>$le秒)趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(services_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (name) - \nsum(increase(services_req_duration_seconds_bucket{le=\"$le\",app=\"$appname\",envtype=\"$envtype\"}[1m])) by (name)) >0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "所选时段内慢请求(>$le秒)的分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(services_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (name) - sum(increase(services_req_duration_seconds_bucket{le=\"$le\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by(name)) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}