{
 "title": "java-alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appGroup",
    "label": "产品线",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app_group)  "
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_group=~\"$appGroup\",envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   { "name": "logBaseUrl", "query": "https://rzy.huazhucorp.com" }
  ]
 },
 "panels": [
  {
   "title": "全局报警统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "报警类型分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(ALERTS{envtype=~\"$envtype\",alertstate=\"firing\"}) by (alertname)",
       "legendFormat": "{{alertname}} "
      }
     ]
    },
    {
     "title": "应用firing的报警数",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 11 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(ALERTS{envtype=~\"$envtype\",alertstate=\"firing\"}) by (app)",
       "legendFormat": "{{app}} "
      }
     ]
    }
   ]
  },
  { "title": "应用报警统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP 接口",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(http_server_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[2m]))) OR on() vector(0)",
     "legendFormat": "点击查看HTTP接口统计"
    }
   ]
  },
  {
   "title": "HTTP接口5xx占比 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_total{status=~\"5..\",group!~\"OperationHandler|default\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[1m])) / sum(increase(http_server_request_total{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[1m]))) >=0 OR on() vector(0)",
     "legendFormat": "点击查看AccessLog"
    }
   ]
  },
  {
   "title": "应用节点",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "instance_health_status{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RPC调用",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[2m]))\n or on() vector(0)",
     "legendFormat": "点击查看RPC统计"
    }
   ]
  },
  {
   "title": "RPC异常请求占比 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_total{status=~\"4..|5..\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[1m])) / sum(increase(http_client_request_total{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[1m]))) >=0 OR on() vector(0)",
     "legendFormat": "点击查看RPC统计"
    }
   ]
  },
  {
   "title": "Error日志 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(logback_events_total{level=\"error\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[60s]) OR increase(log4j2_events_total{level=\"error\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[60s]) OR increase(log4j1_events_total{level=\"error\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[60s])) by (app))",
     "legendFormat": "点击查看应用日志"
    }
   ]
  },
  {
   "title": "GC频率 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(instance_gc_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[1m])) by(app))",
     "legendFormat": "点击查看GC统计"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_cgroup_cpu_cfs_quota_seconds{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"} * 10) / sum(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}))  > 0",
     "legendFormat": "点击查看CPU规格"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cgroup_memory_limit_bytes{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}) / sum(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"})",
     "legendFormat": "点击查看内存规格"
    }
   ]
  },
  {
   "title": "报警信息",
   "type": "graph",
   "gridPos": { "h": 15, "w": 22, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}",
     "legendFormat": "{{alertname}} | {{alertstate}} - {{instance}} "
    }
   ]
  }
 ]
}