{
 "title": "measured-method-sla",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": " Deployment Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "Application (support sug)",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "method",
    "label": "Java Method",
    "query": {
     "query": "label_values(services_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Method time consumption waterline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "services_req_duration_seconds{name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "services_req_duration_seconds{name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "services_req_duration_seconds{name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Horizontal comparison of long-tail method requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95(95%) time consumption",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " services_req_duration_seconds{quantile=\"0.95\",name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "P99(99%) time consumption",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " services_req_duration_seconds{quantile=\"0.95\",name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "P999(99.9%) time consuming",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " services_req_duration_seconds{quantile=\"0.95\",name=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Abnormal distribution of Method in the selected period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Exception type distribution in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(services_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",name=~\"$method\"}[$__range])) by (exception)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{exception}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SQL Exception node distribution in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(services_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",name=~\"$method\"}[$__range])) by (instance)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Method: $method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "sql" },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(services_req_duration_seconds_count{name=~\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (app_cluster) ",
     "legendFormat": "Cluster: {{app_cluster}}"
    },
    {
     "expr": "sum(irate(services_req_duration_seconds_count{name=~\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time consumption histogram in the selected period",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(services_req_duration_seconds_bucket{name=~\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Exception trend in the last two minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(services_req_error_total{name=~\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (exception)",
     "legendFormat": "{{exception}}"
    }
   ]
  }
 ]
}