{
 "title": "jvm-overview",
 "description": "节点指标",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\",instance=\"$instance\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "各节点JVM内存池概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC 频次 [ 1m ]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "次/分钟" } },
     "yaxes": [
      { "format": "次/分钟" }
     ],
     "targets": [
      {
       "expr": "increase(instance_gc_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\"}[70s])",
       "legendFormat": "{{instance}} - {{name}} "
      }
     ]
    },
    {
     "title": "GC 最大停顿时长",
     "type": "graph",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{envtype=~\"$envtype\",app=\"$appname\"}",
       "legendFormat": "{{instance}} - {{action}} ({{cause}}) "
      }
     ]
    },
    {
     "title": "老年代(Old Gen)已用内存",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",id=~\".+Old.+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "新生代(Eden Gen)已用内存",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",id=~\".+Eden.+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Survivor Space 已用内存",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",id=~\".+Survivor.+\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "堆内存使用率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\", area=\"heap\"}) by(instance) /  sum(jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\", area=\"heap\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "部署环境和系统信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "进程启动时长",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{envtype=\"${envtype}\",app=\"$appname\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Apollo 配置 & Exception",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 14, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(config_apollo_release_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟配置文件更新的次数"
      },
      {
       "expr": "increase(config_apollo_changedkeys_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟累计变动的配置项"
      },
      {
       "expr": "increase(config_apollo_exception_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "{{cause}} [ 2m ]"
      }
     ]
    },
    {
     "title": "宿主机累计运行",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_uptime_seconds{envtype=\"$envtype\",app=\"$appname\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "节点容量规格",
     "type": "stat",
     "gridPos": { "h": 3, "w": 18, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_cgroup_cpu_cfs_quota_seconds{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"} * 10",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "CPU Quota",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "node_cgroup_memory_limit_bytes{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "内存 Quota",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "-Xmx",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "process_files_max_files{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max FileDescriptor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "app_disk_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "磁盘容量",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "system_processors_cnt{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "宿主机CPU",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "system_memory_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "宿主机内存",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "system_memory_swap_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "SWAP分区",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DNS缓存",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dns_cache_ttl_seconds{envtype=~\"$envtype\",app=\"$appname\",name=\"positive.policy\",instance=\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "DNS缓存",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "集群",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{app_cluster}}"
      }
     ]
    },
    {
     "title": "时区",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{user_timezone}}"
      }
     ]
    },
    {
     "title": "File Encoding",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{file_encoding}}"
      }
     ]
    },
    {
     "title": "JAVA版本",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{java_version}}"
      }
     ]
    },
    {
     "title": "Class版本",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{class_version}}"
      }
     ]
    },
    {
     "title": "JVM版本",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{jvm_version}}"
      }
     ]
    },
    {
     "title": "OS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{os_name}}"
      }
     ]
    },
    {
     "title": "OS Arch",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{os_arch}}"
      }
     ]
    },
    {
     "title": "OS Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_runtime_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{os_version}}"
      }
     ]
    },
    {
     "title": "进程ID(PID)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_pid{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "CI Build Number",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_git_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{build_number}}"
      }
     ]
    },
    {
     "title": "部署的Git分支",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_git_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{branch}}"
      }
     ]
    },
    {
     "title": "最近的构建时间",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_git_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{build_time}}"
      }
     ]
    },
    {
     "title": "总内存",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "instance_mem_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "pom version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_git_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{build_version}}"
      }
     ]
    },
    {
     "title": "发布时的Git CommitId",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_git_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{commit_id}}"
      }
     ]
    },
    {
     "title": "宿主机IP",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_deployment_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{hostip}}"
      }
     ]
    },
    {
     "title": "k8s node ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_info{pod=\"$pod\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "k8s pod name",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 9, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_deployment_info{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "宿主机内存统计",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "1 -(system_memory_free_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"} /  system_memory_total_bytes)",
       "legendFormat": "宿主机内存使用率"
      },
      {
       "expr": "system_memory_free_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "宿主机空闲内存(free)"
      },
      {
       "expr": "system_memory_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "宿主机总内存(total)"
      },
      {
       "expr": "system_memory_swap_free_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "宿主机Swap分区剩余大小(free)"
      },
      {
       "expr": "system_memory_swap_total_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "宿主机Swap分区大小(total)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM内存池统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM内存池最大配置",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 21, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}})"
      }
     ]
    },
    {
     "title": "堆(Heap)内存",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "已用的(Used)堆内存"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "最大可用的(-Xmx)堆内存"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "已提交的(Committed)堆内存"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"heap\"}) /  sum(jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "堆内存使用率"
      }
     ]
    },
    {
     "title": "堆外(Off Heap)内存",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "已用的(Used)堆外内存池"
      },
      {
       "expr": "netty_memory_direct_inuse_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "Netty已用的Direct Memory"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "最大可用的(Max)堆外内存"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\", area=\"nonheap\"}) / sum(jvm_memory_max_bytes)",
       "legendFormat": "堆外内存使用率"
      }
     ]
    },
    {
     "title": "GC 内存分配",
     "type": "graph",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "新生代(Young Gen)每秒增加的字节"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "老年代(Old Gen)每秒增加的字节"
      }
     ]
    },
    {
     "title": "已使用的JVM内存池 ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}({{area}}) "
      }
     ]
    },
    {
     "title": "Classloader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "当前已加载的class"
      },
      {
       "expr": "increase(jvm_classes_started_loaded_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟累计加载的class"
      },
      {
       "expr": "increase(jvm_classes_unloaded_classes_total{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
       "legendFormat": "近两分钟累计卸载的class"
      }
     ]
    },
    {
     "title": "NIO BufferPool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}_已用内存"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}_最大可用内存"
      }
     ]
    },
    {
     "title": "NIO BufferPool Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
       "legendFormat": "{{id}}_count"
      }
     ]
    }
   ]
  },
  { "title": "JVM GC耗时统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "所选时段内GC统计",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])) by(cause)",
     "legendFormat": "{{cause}}"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range]) ) by(cause)",
     "legendFormat": "{{cause}}"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])) by(cause) / sum(increase(jvm_gc_pause_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range]) ) by(cause) ",
     "legendFormat": "{{cause}}"
    },
    {
     "expr": "max_over_time(jvm_gc_pause_seconds_max{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])",
     "legendFormat": "{{cause}}"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])) by(cause) / \nignoring(cause) group_left sum(increase(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "GC 停顿时长",
   "type": "graph",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(instance_gc_duration_seconds_sum{app=\"$appname\",instance=\"$instance\",envtype=~\"$envtype\"}[2m]) / rate(instance_gc_duration_seconds_count{app=\"$appname\",instance=\"$instance\",envtype=~\"$envtype\"}[2m]) ",
     "legendFormat": "{{name}} - 平均停顿"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
     "legendFormat": "{{action}} ({{cause}})  - 最大停顿时长"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m]) / rate(jvm_gc_pause_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[2m])",
     "legendFormat": "{{action}} ({{cause}}) - 平均停顿"
    },
    {
     "expr": "jvm_gc_concurrent_phase_time_seconds_max{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}",
     "legendFormat": "{{action}} ({{cause}})  - 并发(concurrent)回收最大耗时"
    }
   ]
  },
  {
   "title": "GC 原因与频次",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "次/分钟" } },
   "yaxes": [
    { "format": "次/分钟" }
   ],
   "targets": [
    {
     "expr": "increase(instance_gc_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[70s])",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "increase(jvm_gc_pause_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[70s])",
     "legendFormat": "{{action}} ({{cause}}) "
    }
   ]
  },
  {
   "title": "所选时段内累计GC次数",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause)",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "所选时段内累计GC耗时",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{envtype=~\"$envtype\",app=\"$appname\",instance=\"$instance\"}[$__range])) by(action,cause) ",
     "legendFormat": "{{action}}  ({{cause}})"
    }
   ]
  }
 ]
}