{
 "title": "kafka-producer-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "Application (support sug)",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": " Node",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "kafkaTemplate",
    "label": "Kafka Template",
    "query": {
     "query": "label_values(spring_kafka_template_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Producer & Kafka Template",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Average time to send Kafka Template messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(spring_kafka_template_seconds_sum{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (name)\n/\nsum(increase(spring_kafka_template_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (name)) ",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Number of messages sent per second by Kafka Template",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(spring_kafka_template_seconds_count{app=\"$appname\",instance=~\"$instance\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of consumption anomalies in Kafka Template in the past minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(spring_kafka_template_seconds_count{app=\"$appname\",instance=~\"$instance\",result=\"failure\"}[1m])) by(name,exception)",
     "legendFormat": "{{name}} - {{exception}}"
    }
   ]
  }
 ]
}