{
 "title": "kafka-consumer-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_consumed_total{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}, topic)"
    }
   },
   {
    "name": "client",
    "label": "消费者",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_consumed_total{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\",topic=~\"$topic\"}, client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Client Coordinator & Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "消费者每分钟Rebalance的次数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_rebalance_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者Rebalance的平均耗时",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_rebalance_latency_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n/sum(increase(kafka_consumer_coordinator_rebalance_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每分钟Group Sync的次数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_sync_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每分钟Group Join的次数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_join_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每分钟发送心跳的次数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_heartbeat_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[1m])) by (instance,client_id)\n",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每分钟Commit的次数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_coordinator_commit_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[2m])) by (instance,client_id)",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每秒发送的字节",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_outgoing_byte_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[2m])) by (instance,client_id)",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每秒发送的Request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_request_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[2m])) by (instance,client_id)",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每秒收到的字节",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_incoming_byte_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[2m])) by (instance,client_id)",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    },
    {
     "title": "消费者每秒收到的Response",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_consumer_response_total{app=\"$appname\",instance=~\"$instance\",client_id=~\"$client\"}[2m])) by (instance,client_id)",
       "legendFormat": "{{instance}} - {{client_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Topic & Kafka Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Topic每秒消费的消息数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_fetch_manager_records_consumed_total{app=\"$appname\",instance=~\"$instance\",topic=~\"$topic\"}[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "客户端Topic消费延迟(Lag)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{app=\"$appname\",instance=~\"$instance\",topic=~\"$topic\"}) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Listener 消息处理平均耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(spring_kafka_listener_seconds_sum{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (name)\n/\nsum(increase(spring_kafka_listener_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (name)) ",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Kafka Listener 每秒消费的消息数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(spring_kafka_listener_seconds_count{app=\"$appname\",instance=~\"$instance\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Kafka Listener 近一分钟消费异常的次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(spring_kafka_listener_seconds_count{app=\"$appname\",instance=~\"$instance\",result=\"failure\"}[1m])) by(name,exception)",
     "legendFormat": "{{name}} - {{exception}}"
    }
   ]
  }
 ]
}