{
 "title": "local-cache-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "localcache",
    "label": "Local Cache",
    "query": {
     "query": "label_values(cache_size{service=\"$appname\",instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "副本数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"$appname\"}"
    }
   ]
  },
  {
   "title": "应用节点和 Pod Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "process_uptime_seconds{app=\"$appname\",envtype=\"$envtype\"}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{ pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "各节点组件流量概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\"}[2m])) ",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",envtype=~\"$envtype\",app=\"$appname\"}[2m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",envtype=~\"$envtype\",app=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_consumed_total{service=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - consumed"
      },
      {
       "expr": "sum(irate(rabbitmq_published_total{service=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - published"
      }
     ]
    },
    {
     "title": "Logback 日志",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m]))\n",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Logback  Level ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m]))  by (instance,level)",
       "legendFormat": "{{instance}}  - {{level}}"
      }
     ]
    }
   ]
  },
  { "title": "Local Cache (Cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "集群 Local Cache QPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cache_gets_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\"}[2m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "集群每分钟 Local Cache Miss ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_gets_total{result=\"miss\",app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\"}[1m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "集群每分钟 Local Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_evictions_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\"}[1m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "集群每分钟  Local Cache Put",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cache_puts_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\"}[1m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Local Cache (Instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "当前节点缓存大小",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_size{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "当前节点缓存命中率",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{result=\"hit\",app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[2m])) by(instance,name) / sum(rate(cache_gets_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[2m])) by (instance,name)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "当前节点每分钟 Local Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "当前节点每分钟 Local Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "当前节点每分钟 Local Cache Put",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[70s])) by(name,instance)",
       "legendFormat": "{{name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内当前节点累计Cache Hit",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"hit\",app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内当前节点累计Cache Miss",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 45 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{result=\"miss\",app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内当前节点累计Cache Eviction",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 53 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_evictions_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内当前节点累计Cache Put",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(cache_puts_total{app=\"$appname\",envtype=\"$envtype\",name=~\"$localcache\", instance=~\"$instance\"}[$__range])) by (instance,name)",
       "legendFormat": "{{name}}  - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}