{
 "title": "listener-overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appGroup",
    "label": "产品线",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app_group)  "
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_group=~\"$appGroup\",envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "queue",
    "label": "队列",
    "query": {
     "query": "label_values(spring_rabbitmq_listener_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "队列每秒消费的消息数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(spring_rabbitmq_listener_seconds_count{app=\"$appname\",instance=~\"$instance\",queue=~\"$queue\",envtype=~\"$envtype\"}[2m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "队列近一分钟消费异常的次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(spring_rabbitmq_listener_seconds_count{app=\"$appname\",instance=~\"$instance\",result=\"failure\",queue=~\"$queue\",envtype=~\"$envtype\"}[1m])) by (queue,exception)",
     "legendFormat": "{{queue}} - {{exception}}"
    }
   ]
  },
  {
   "title": "队列消息处理平均耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(spring_rabbitmq_listener_seconds_sum{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",queue=~\"$queue\"}[1m])) by (queue)\n/\nsum(increase(spring_rabbitmq_listener_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",queue=~\"$queue\"}[1m])) by (queue)) ",
     "legendFormat": "{{queue}} "
    }
   ]
  }
 ]
}