{
 "title": "mq-overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appGroup",
    "label": "产品线",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app_group)  "
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_group=~\"$appGroup\",envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   { "name": "logBaseUrl", "query": "https://rzy.huazhucorp.com" }
  ]
 },
 "panels": [
  { "title": "全局统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rabbit生产者(Producer)统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_published_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m]))",
     "legendFormat": "近一分钟 published 的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_failed_to_publish_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m]))",
     "legendFormat": "近一分钟 publish failed 的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_acknowledged_published_total{app=\"$appname\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "近一分钟 acknowledged published的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_not_acknowledged_published_total{app=\"$appname\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "近一分钟 not acknowledged published 的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_unrouted_published_total{app=\"$appname\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "近一分钟 unrouted published 的消息"
    }
   ]
  },
  {
   "title": "Rabbit消费者(Consumer)统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_consumed_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])) ",
     "legendFormat": "近一分钟 consumed 的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_acknowledged_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])) ",
     "legendFormat": "近一分钟 acknowledged 的消息"
    },
    {
     "expr": "sum(increase(rabbitmq_rejected_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m]))",
     "legendFormat": "近一分钟 rejected 的消息"
    }
   ]
  },
  {
   "title": "连接池 ( ConnectionFactory ) 统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}) by (name)",
     "legendFormat": "{{name}} - channels"
    },
    {
     "expr": "sum(rabbitmq_connections{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}) by (name)",
     "legendFormat": "{{name}} - connections"
    }
   ]
  },
  {
   "title": "Rabbit生产者详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "近一分钟 published",
     "type": "graph",
     "description": "调用Channel#basicPublish发送消息的次数",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_published_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 publish failed",
     "type": "graph",
     "description": "调用Channel#basicPublish发送消息时异常的次数",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_failed_to_publish_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 acknowledged published",
     "type": "graph",
     "description": "ack confirm events:  messages handled successfully",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_acknowledged_published_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 not acknowledged published",
     "type": "graph",
     "description": "nacks confirm events : messages lost by the broker",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_not_acknowledged_published_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 unrouted published",
     "type": "graph",
     "description": "消息找不到路由时的回调(PublishReturn)次数",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_unrouted_published_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rabbit消费者详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "近一分钟 consumed",
     "type": "graph",
     "description": "调用Channel#basicGet获取消息的次数",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_consumed_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 acknowledged",
     "type": "graph",
     "description": "调用Channel#basicAck确认消费的次数",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_acknowledged_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "近一分钟 rejected （Nack + BasicReject )",
     "type": "graph",
     "description": "调用Channel#basickNack|basicReject消费失败的次数",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(rabbitmq_rejected_total{app=\"$appname\",instance=~\"$instance\",envtype=~\"$envtype\"}[1m])",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  }
 ]
}