{
 "title": "redis-cache-overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\",app=\"$appname\",envtype=\"$envtype\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "副本数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"$appname\"}"
    }
   ]
  },
  {
   "title": "应用节点和 Pod Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "process_uptime_seconds{app=\"$appname\",envtype=\"$envtype\"}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{ pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$appname-[0-9a-z]+-[0-9a-z]+\"})"
    }
   ]
  },
  {
   "title": "各节点组件流量概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\"}[2m])) ",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(http_server_request_duration_seconds_count{envtype=~\"$envtype\",app=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",envtype=~\"$envtype\",app=\"$appname\"}[2m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",envtype=~\"$envtype\",app=\"$appname\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ 流量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rabbitmq_consumed_total{app=\"$appname\",envtype=\"$envtype\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - consumed"
      },
      {
       "expr": "sum(irate(rabbitmq_published_total{app=\"$appname\",envtype=\"$envtype\"}[2m]))  by (instance)",
       "legendFormat": "{{instance}} - published"
      }
     ]
    },
    {
     "title": "Logback 日志",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m]))\n",
       "legendFormat": "total"
      },
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Logback  Level ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 35 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{envtype=~\"$envtype\",app=\"$appname\"}[2m]))  by (instance,level)",
       "legendFormat": "{{instance}}  - {{level}}"
      }
     ]
    }
   ]
  },
  { "title": "Redis ConnectionPool (Cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "集群 Redis Command",
   "type": "stat",
   "description": "所有节点每秒执行的Redis Command",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[2m]))"
    }
   ]
  },
  {
   "title": "集群TCP连接统计",
   "type": "graph",
   "description": "所有节点的Redis 连接池统计",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[2m]))",
     "legendFormat": "每秒执行的Redis命令(Borrow)"
    },
    {
     "expr": "sum(irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[2m]))",
     "legendFormat": "每秒归还连接的次数(Return)"
    },
    {
     "expr": "sum(increase(commonspool2_con_created_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[1m]))",
     "legendFormat": "每分钟创建的TCP连接"
    },
    {
     "expr": "sum(increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\"}[1m]))",
     "legendFormat": "每分钟销毁的TCP连接"
    },
    {
     "expr": "sum(increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
     "legendFormat": "每分钟由定时任务触发销毁的TCP连接"
    },
    {
     "expr": "sum(increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",service=\"$appname\"}[1m]))",
     "legendFormat": "每分钟由获取连接触发销毁的TCP连接"
    }
   ]
  },
  {
   "title": "Redis Connection Pool (Instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "当前节点连接池统计",
     "type": "graph",
     "description": "单个节点的 Redis 连接池使用率和配置",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"} / commonspool2_con_config_max{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 使用率"
      },
      {
       "expr": "commonspool2_con_active{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}}  - 当前活跃的连接数"
      },
      {
       "expr": "commonspool2_threads_waits{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 池耗尽时阻塞等待的线程数"
      },
      {
       "expr": "commonspool2_con_idle{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 当前的空闲连接数"
      },
      {
       "expr": "commonspool2_con_config_max{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最大连接数"
      },
      {
       "expr": "commonspool2_con_config_idle_max{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最大空闲连接数"
      },
      {
       "expr": "commonspool2_con_config_idle_min{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": "{{comp_name}} - 最小空闲连接数"
      }
     ]
    },
    {
     "title": "当前节点TCP连接统计",
     "type": "graph",
     "description": "单个节点最近一分钟的TCP连接统计",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Redis命令的平均耗时[ms]"
      },
      {
       "expr": "irate(commonspool2_con_borrowed_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - 每秒执行的Redis命令(Borrow)"
      },
      {
       "expr": "irate(commonspool2_con_returned_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[2m])",
       "legendFormat": " {{comp_name}} - 每秒归还连接的次数(Return)"
      },
      {
       "expr": "increase(commonspool2_con_created_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}}  - 每分钟创建的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟销毁的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_byevictor_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟由定时任务触发销毁的TCP连接"
      },
      {
       "expr": "increase(commonspool2_con_destroyed_onborrow_total{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}[1m])",
       "legendFormat": " {{comp_name}} - 每分钟由获取连接触发销毁的TCP连接"
      }
     ]
    },
    {
     "title": "当前节点连接池耗时统计",
     "type": "graph",
     "description": "单个节点的Redis连接池耗时统计",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "commonspool2_con_active_meantime_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - Redis命令的平均耗时"
      },
      {
       "expr": "commonspool2_con_idle_meantime_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 连接的平均闲置时长"
      },
      {
       "expr": "commonspool2_con_wait_meantime_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 获取连接的平均等待时长"
      },
      {
       "expr": "commonspool2_con_config_maxwait_mseconds{comp_type=~\"redis.+\",app=\"$appname\",envtype=\"$envtype\",instance=\"$instance\"}",
       "legendFormat": " {{comp_name}} - 客户端配置的最大等待时长"
      }
     ]
    }
   ]
  }
 ]
}