{
 "title": "rpc-sla",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "backend",
    "label": "服务提供方",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},group)"
    }
   },
   {
    "name": "method",
    "label": "RPC调用",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\"},request)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPC耗时分位线",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_request_duration_seconds{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC长尾请求横向对比",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95(95%) 耗时",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_request_duration_seconds{quantile=\"0.95\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "P99(99%) 耗时",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_request_duration_seconds{quantile=\"0.99\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "P999(99.9%) 耗时",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_request_duration_seconds{quantile=\"0.999\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "所选时段内HTTP状态码分布",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP状态码分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_client_request_total{request=\"$method\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "5xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",request=\"$method\"}[$__range])) by (instance)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "4xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",request=\"$method\"}[$__range])) by (instance)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "RPC: $method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "method" },
  {
   "title": "请求量趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_client_request_total{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (app_cluster)",
     "legendFormat": "集群：{{app_cluster}} "
    },
    {
     "expr": "sum(irate(http_client_request_total{status=~\"4..\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (instance) > 0",
     "legendFormat": "{{instance}} - 4xx"
    },
    {
     "expr": "sum(irate(http_client_request_total{status=~\"5..\",request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (instance) > 0",
     "legendFormat": "{{instance}} - 5xx"
    },
    {
     "expr": "sum(irate(http_client_request_total{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "所选时段内的耗时直方图",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_request_duration_seconds_bucket{request=\"$method\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}