{
 "title": "rpc-overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "backend",
    "label": "服务提供方",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},group)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "慢调用统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "近一分钟慢接口趋势  (点击查看更多统计)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[1m])) - \nsum(increase(http_client_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[1m]))"
      }
     ]
    },
    {
     "title": "所选时段内慢接口节点分布 ( 耗时> 2s )",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 13, "x": 6, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (instance) - sum(increase(http_client_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (instance)) >= 1",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内慢请求次数 ( 耗时> 2s )",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (request) - \nsum(increase(http_client_request_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (request)) >= 1",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC状态码/异常统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内FeignClient状态码统计",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_client_request_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "所选时段内服务提供方5xx分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "所选时段内接口请求量 TOP 20 ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "topk(20,(sum(increase(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (request)) > 0)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "所选时段内 HTTP 5xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 HTTP 4xx 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 Exception 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (instance))  > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "所选时段内 Exception 类型分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(http_client_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (class)) > 0",
       "legendFormat": "{{class}} "
      }
     ]
    },
    {
     "title": "所选时段内4xx接口分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",group=~\"$backend\"}[$__range])) by (request) > 0",
       "legendFormat": "{{request}} "
      }
     ]
    }
   ]
  },
  { "title": "RPC调用概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "RPC请求",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[2m]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "RPC调用趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[2m])) by(group) ",
     "legendFormat": "服务提供方: {{group}} "
    },
    {
     "expr": "sum(irate(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[2m])) by(group) > 0",
     "legendFormat": "{{group}} - 5xx"
    },
    {
     "expr": "sum(irate(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[2m])) by(group) > 0",
     "legendFormat": "{{group}} - 4xx"
    },
    {
     "expr": "sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[2m])) by(instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5xx请求占比 [ 1m ]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_total{status=~\"5..\",group!~\"OperationHandler|default\",app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[70s])) / sum(increase(http_client_request_duration_seconds_count{app=\"$appname\",envtype=~\"$envtype\",instance=~\"$instance\"}[70s]))) >=0 OR on() vector(0)"
    }
   ]
  },
  {
   "title": "RPC调用QPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[2m])) by (request,group)",
     "legendFormat": "{{request}} ({{group}})"
    }
   ]
  },
  {
   "title": "RPC调用平均耗时",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "( sum(increase(http_client_request_duration_seconds_sum{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[1m])) by (request,group)\n      /\n      sum(increase(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[1m])) by (request,group) ) >=0",
     "legendFormat": "{{request}} ({{group}})"
    }
   ]
  },
  {
   "title": "近两分钟RPC调用Exception趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_client_exception_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",server=~\"$backend\"}[2m])) by (class,server)",
     "legendFormat": "{{class}} ({{server}})"
    }
   ]
  },
  {
   "title": "所选时段内接口5xx状态码分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[$__range])) by (request,group,status) > 0",
     "legendFormat": "{{status}} - {{request}} ({{group}})"
    }
   ]
  },
  {
   "title": "所选时段内接口4xx状态码分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "      sum(increase(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[$__range])) by (request,group,status) > 0",
     "legendFormat": "{{status}} - {{request}} ({{group}})"
    }
   ]
  },
  {
   "title": "近两分钟RPC调用业务码趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_client_errorcode_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",server=~\"$backend\"}[2m])) by (server,code)",
     "legendFormat": " {{code}} ({{server}})"
    }
   ]
  },
  {
   "title": "RPC服务提供方5xx趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "                        sum(irate(http_client_request_total{status=~\"5..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[3m])) by (group)",
     "legendFormat": "  {{group}}"
    }
   ]
  },
  {
   "title": "RPC服务提供方4xx趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "            sum(irate(http_client_request_total{status=~\"4..\",app=\"$appname\",envtype=\"$envtype\",group=~\"$backend\",instance=~\"$instance\"}[3m])) by (group)",
     "legendFormat": "  {{group}}"
    }
   ]
  }
 ]
}