{
 "title": "slow-rpc",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "backend",
    "label": "服务提供方",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},group)"
    }
   },
   {
    "name": "le",
    "label": "耗时(秒)大于",
    "query": "\"0.1\",\"0.3\",\"0.5\",\"1.0\",\"2.0\",\"3.0\",\"5.0\""
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "所选时段内慢调用统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "慢RPC(>$le秒)的节点分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (instance) - sum(increase(http_client_request__duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (instance)) >= 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "慢RPC(>$le秒)的服务分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (group) - sum(increase(http_client_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (group)) >= 1",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "所选时段内慢RPC(>$le秒)分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (request) - sum(increase(http_client_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[$__range])) by (request)) >= 1",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "近一分钟慢RPC(>$le秒)趋势",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "次/分钟" } },
   "targets": [
    {
     "expr": "(sum(increase(http_client_request_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[1m])) by (request) - sum(increase(http_client_request_duration_seconds_bucket{le=\"$le\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\",group=~\"$backend\"}[1m])) by (request)) >= 1",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}