{
 "title": "sql-overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "Application (support sug)",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slow SQL Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow SQL Trend in the Last Minute (Click to View More Statistics)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(mybatis_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) - \nsum(increase(mybatis_req_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m]))"
      }
     ]
    },
    {
     "title": "Distribution of slow SQL nodes in the selected period (> 2s)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 11, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance) - sum(increase(mybatis_req_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (instance)) >= 1",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of slow SQL statements in the selected period (> 2s)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_duration_seconds_bucket{le=\"+Inf\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (sql) - \nsum(increase(mybatis_req_duration_seconds_bucket{le=\"2.0\",app=\"$appname\",envtype=\"$envtype\"}[$__range])) by (sql)) >= 1 ",
       "legendFormat": "{{sql}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics and Abnormal Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Execution Statistics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m]))",
       "legendFormat": "SQL statements executed per second"
      },
      {
       "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (command)",
       "legendFormat": " {{command}} statements executed per second"
      },
      {
       "expr": "sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (exception) > 0",
       "legendFormat": "About one minute{{exception}}"
      }
     ]
    },
    {
     "title": "TOP 20 SQL requests in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "topk(20,(sum(increase(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (sql)) > 0)",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": " SQL Exception node distribution in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (instance)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": " SQL Exception type distribution in the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (exception)) > 0",
       "legendFormat": "{{exception}}"
      }
     ]
    },
    {
     "title": " SQLID distribution of errors reported during the selected period",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (sql)) > 0",
       "legendFormat": "{{sql}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL request volume/error ranking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "SQL statements executed per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request volume trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (app_cluster)",
     "legendFormat": "Cluster: {{app_cluster}}"
    },
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (instance) > 0",
     "legendFormat": "{{instance}} - exception"
    }
   ]
  },
  {
   "title": "SQL Exception ratio in the last minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) / sum(increase(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "SQL QPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[2m])) by (sql) ",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "Average SQL Time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "( sum(increase(mybatis_req_duration_seconds_sum{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (sql)\n/\nsum(increase(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[1m])) by (sql) ) >= 0",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "SQL Exception TOP 20 in the selected period",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(20,(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\"}[$__range])) by (sql,exception)) > 0)",
     "legendFormat": "{{exception}} - {{sql}}"
    }
   ]
  }
 ]
}