{
 "title": "sql-sla",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envtype",
    "label": "部署环境",
    "query": {
     "query": "label_values(registry_metrics_vendor{app_type=\"java\"},envtype)"
    }
   },
   {
    "name": "appname",
    "label": "应用 ( 支持sug )",
    "query": {
     "query": "label_values(registry_metrics_vendor{envtype=\"$envtype\",app_type=\"java\"},app)"
    }
   },
   {
    "name": "sql",
    "label": "SQL",
    "query": {
     "query": "label_values(mybatis_req_duration_seconds_count{app=\"$appname\",envtype=\"$envtype\"},sql)"
    }
   },
   {
    "name": "instance",
    "label": "节点",
    "query": {
     "query": "label_values(registry_metrics_vendor{app=\"$appname\",envtype=~\"$envtype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL耗时水位线",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{quantile}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SQL长尾请求横向对比",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95(95%) 耗时",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{quantile=\"0.95\",sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "P99(99%) 耗时",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{quantile=\"0.99\",sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "P999(99.9%) 耗时",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mybatis_req_duration_seconds{quantile=\"0.999\",sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "所选时段内SQL异常分布",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "所选时段内 SQL Exception 类型分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",sql=~\"$sql\"}[$__range])) by (exception)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{exception}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "所选时段内 SQL Exception 节点分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(mybatis_req_error_total{app=\"$appname\",envtype=\"$envtype\",instance=~\"$instance\",sql=~\"$sql\"}[$__range])) by (instance)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "SQL: $sql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "sql" },
  {
   "title": "QPS 趋势",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (app_cluster)",
     "legendFormat": "集群: {{app_cluster}}"
    },
    {
     "expr": "sum(irate(mybatis_req_duration_seconds_count{sql=\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "所选时段内的耗时直方图",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mybatis_req_duration_seconds_bucket{sql=~\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "近两分钟Exception趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mybatis_req_error_total{sql=~\"$sql\",app=\"$appname\",instance=~\"$instance\",envtype=\"$envtype\"}[2m])) by (exception)",
     "legendFormat": "{{exception}}"
    }
   ]
  }
 ]
}